M48
; DRILL file {KiCad (6.0.2-0)} date 2022 June 23, Thursday 22:24:59
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-23T22:24:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.0413Y-4.045
X4.0413Y-5.8429
X4.7421Y-4.0429
X4.7421Y-5.8429
T0
M30
